services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "file:/app/database/murasaki.db"
      FILE_PATH: "/file"
    volumes:
      - ./database:/app/database
      - ./data/files:/app/public/file
      - ./data/template:/app/public/template
